### ISSUE TITLE
UI Pet Peeve: I hate entering my password twice to use CashShuffle

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#106]
... and I bet you I wouldn't be the only one to hate that.

How do you guys feel about my doing a hack whereby if you JUST entered your password in the "wallet wizard" UI, that password gets forwarded on to cashshuffle for its use.

If cashshuffle doesn't want it, then it gets dropped using normal python del/GC.

What do you guys say?  I think users would feel our app is a little dorky in that it makes you input your password twice at wallet startup.

**Comment by emergent-reasons** [comment]
It is preeeetty dorky. :D Definitely needs to be one time if possible.

**Comment by cculianu** [comment]
... aaand.. It's done!
