### ISSUE TITLE
should not prompt for wallets that cannot use shuffle

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#12]
From what I understand the following wallet types cannot use shuffle since they require manual intervention:

- Multisig
- Hardware wallets
- Watching-only wallets (cold wallets)

It doesn't make sense for the popup to ask if I want to shuffle when it wouldn't be possible anyway.

Also, we should probably not do shuffling on 'Imported private key' wallets since they don't have infinite lists of new addresses.

**Comment by cculianu** [comment]
Good point!

I already disabled the watching-only wallets.

Will do so for hardware and multisig as well.

Good catch!
