### ISSUE TITLE
Potential 'race condition' between Send tab (normal wallet use) and Cash Shuffle

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#14]
Consider that previous to Cash Shuffle Electron Cash operated under the following invariant:

**"The set of coins considered for spending in the 'Send' tab is a set that does not (typically) become spuriously invalidated without the user doing something."**

Said another way: **At any given time when a wallet is synchronized and up-to-date, any given subset of all spendable UTXOs remains valid until the user takes an action.**

With CashShuffle enabled, that simple invariant **no longer holds**.

As a result there is a very likely race condition that can occur between Cash Shuffle's background shuffling and normal use of the wallet.

The scenario:

- A user can sign a tx with set A of coins (say, they say "Spend Max"). 
- User is busy previewing the tx and deciding whether to broadcast it or not. Perhaps they take a smoke break.
- Then, at the same time, CashShuffle shuffles some of the coins in set A, thus spending the outputs in set A.  The set of spendable coins is now some other set != set A.
- User returns to their preview, decides to broadcast.  User tries to broadcast a tx involving set A and gets an error message.

I guarantee you that this will happen.  And it's really crappy UX.

---

If the above seems like paranoia -- consider that even under normal 'Send' tab use you can hit 'Send' and the wallet will immediately get errors as available amounts and the coin set changes. One minute "Insufficient Funds", the next minute it would work, the next it's "Insufficient Funds" again.

---

This situation is especially troublesome when the user hits **Max** in the send tab.

**Max** writes the value  **'!'** to the internal **'Amount'** variable.  The 'max' amount they are quoted on-screen won't be the same amount they get some time later when they hit **'Send'**.   As a result: ***The wallet just lied to them about how much they're sending.***

---

There are strategies to avoid this situation that the wallet can employ which would involve cooperation/communication between the shuffling process and the coin chooser and/or the Send tab.

Or perhaps even decent real-time display of actual amounts available (broken down by confirmed/unconfirmed/frozen/frozen for shuffling, etc) in the Send tab or status bar would do the trick.

**We need to consider and implement these strategies!**

---

**Potential implication for plugins:** Likely plugins that craft tx's such as the Scheduled Payment plugin (authored by Roger Taylor) and the Donate Spare Change plugin will also be affected by Cash Shuffle -- but that's a secondary consideration since the onus typically should be on plugin authors to maintain compatibility with extant versions of EC.  It's just something to keep in mind as a potential issue for extant plugins.

**Comment by cculianu** [comment]
Perhaps some pictures are worth 1000 words.

---
Here I hit the "Max" button which shows me 28.xxxx as the amount to be sent.
 
<img width="975" alt="screen1" src="https://user-images.githubusercontent.com/266627/49446000-d946e280-f7db-11e8-828a-da39d41b2fdb.png">

Then.. on the preview screen I'm given a different amount:

<img width="760" alt="screen 2" src="https://user-images.githubusercontent.com/266627/49446032-eb288580-f7db-11e8-8807-567c2a322a75.png">

---

This is the race condition in action.

Returning to the Send screen still shows me the higher amount.  Some time later after coins are shuffled the amounts will change **yet again**.

**Comment by fyookball** [comment]
We should address this issue as follows:

First of all, I was under the impression that once an amount is specified, the coin will be chosen.  Coin selection should not change on its own because of freezing/unfreezing.  If that is happening, we should determine why; I see no reason to allow that behavior.

In the case when there is an existing UTXO that is no longer present because it was just mixed, the wallet would naturally be returning an error from the server ("missing inputs" etc).  I propose that we add functionality to prompt user to turn off CashShuffling if any server error happens.

We can display the normal server error and add the following text:

**This error may have been caused by the wallet trying to send a coin that was already shuffled.  Please try again.  If the error persists, it is recommended to temporarily disable CashShuffle.**

**Comment by cculianu** [comment]
> First of all, I was under the impression that once an amount is specified, the coin will be chosen. Coin selection should not change on its own because of freezing/unfreezing. If that is happening, we should determine why; I see no reason to allow that behavior.

Nope. Nothing is chosen until an unsigned tx is generated in the preview screen (if you do preview) or a tx is genereated on-the-fly if you click "sign".  And even if it were -- no guarantees the UTXO sticks around.

> We can display the normal server error and add the following text:

> This error may have been caused by the wallet trying to send a coin that was already shuffled. Please try again. If the error persists, it is recommended to temporarily disable CashShuffle.

I think that just makes the app crappier than it is now and reduces user comfort and perception that they are in a good world when they are using Electron Cash.  You are asking for users to get frustrated.

Do you like it when you go to the bank to use the ATM and it asks you to please try again?

What about when you order Chinese food and the guy on the phone asks you to hang up and call again?

Don't "misunderestimate" how frustrated people can feel when they get an error screen.  I'm a power user and it would certainly make me angry and want to turn off cashshuffle if that happened.

I really think im_uname's simple suggestion of CashShuffle Enabled == only shuffled UTXOs solves a lot of problems and is easy to understand for people.

**Comment by fyookball** [comment]
if im_uname's solution will handle it then it seems an ok solution.  But is it is still possible to have a problem?  Specifically: If the user turns off shuffling while a shuffle is in progress.  I suppose it would be possible but unlikely and an acceptable limitation?

**Comment by cculianu** [comment]
You know even if we just give them good real-time stats in the UI it may be enough for them to know what's going on.  Like some amount breakdowns or something that update in real-time.. so they know what they are in for.

The problem isn't so bad if at least you are up to the minute informed on what's happening..

**Comment by cculianu** [comment]
> I suppose it would be possible but unlikely and an acceptable limitation?

Yeah it would still be possible -- maybe with some real-time stats breaking down the amounts in question right in the Send tab it would make more sense to users.  Hmm.

I'm glad you're really flexible on this one Jonald!  I know it's a tough pill to swallow -- the "CashShuffle == only shuffled spending".  But once you embrace that dark side.. you see the advantages of it.

It's radical for sure..  Thanks for being flexible on it.

I'll try and see if we can avoid it.  Maybe it's not so bad in practice with good realtime stats.

**Comment by fyookball** [comment]
well as long as its clear to the user that they may have funds that the wallet isn't currently allowed to send , and why this is so....and how to change it.

**Comment by cculianu** [comment]
Ok, right on. I'll try my best to make it good.

If it sucks we always have the nuclear option of UTXO Nazi:  "NO UNSHUFFLED FOR YOU!!" 👍

**Comment by cculianu** [comment]
I believe the "Spend only shuffled coins" thing I just implemented fixes this issue.

Here is a screenshot:

<img width="782" alt="screen shot 2018-12-11 at 2 47 44 pm" src="https://user-images.githubusercontent.com/266627/49801981-5c27ea00-fd54-11e8-8e2c-1881b8b85208.png">
