### ISSUE TITLE
Send tab should include a checkbox for "spend only shuffled coins"

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#15]
The user should be offered such an option on sending.  Perhaps it could be a tri-state:

1. Spend only shuffled coins
2. Spend only unshuffled coins
3. Don't care.

Coin Chooser should take this option into account when choosing coins for a tx.

**Comment by fyookball** [comment]
Ok to include this fix in initial release.

**Comment by cculianu** [comment]
This has now been implemented in the way imaginary_username suggested.  The send tab only spends shuffled coins if cashshuffle is on.  Here is a screenshot:

<img width="782" alt="screen shot 2018-12-11 at 2 47 44 pm" src="https://user-images.githubusercontent.com/266627/49801765-bd02f280-fd53-11e8-8bd2-48aa6d4a9545.png">
