### ISSUE TITLE
Label tx's as "CashShuffled" and addresses "shuffled" 

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#16]
After CashShuffle performs a shuffle it should call `wallet.set_label` to do the following:

- Set the label for the txid of the shuffle tx to 'CashShuffle' (or something similar)
- Set the label for the address the shuffled coin lives on now to 'Shuffled' or something similar.

This way the user knows what is going on when he sees tx's appear in his wallet history and very easily knows which addresses contain shuffled coins from just glancing at the History/Address/Coins tab.

**Comment by fyookball** [comment]
I like the history one.  Not sure about the address one though.  If the user accidentally re-uses an address the label would be incorrect and misleading.

**Comment by cculianu** [comment]
Good point about the address thing making users feel "safe" that it means "shuffled" when it's not.

I'll just do the history one.

**Comment by cculianu** [comment]
Ok, this is now done.  CashShuffle tx's are labelled 'CashShuffle Transaction' in the history, but the address label remains untouched.
