### ISSUE TITLE
CashShuffle should perhaps live in its own tab

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#17]
It's great that the UTXO tab is modified under cash shuffle but the lack of a clear UI for CashShuffle could be a hurdle.

It might be nice to also craft a custom tab for CashShuffle that also contains:

- UTXOList
- Perhaps some other stats
- Feedback to the user if there are issues that need their attention (say, the server is dead)
- Etc...

**Comment by zquestz** [comment]
Looks like this has been incorporated into the send tab, do we need this issue open?

**Comment by cculianu** [comment]
Ok, can close.
