### ISSUE TITLE
Coins Tab (UTXOList) is off by default -- consider turning it on by default?

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#18]
Right now, the only real feedback to the user that CashShuffle is doing anything is the 'Coins' tab (and the History tab after a shuffle completes).

However, most users don't even know the 'Coins' tab exists.  A default install of Electron Cash has the 'Coins' tab hidden by default (off). Users must go into the main menu to enable this tab.

- Consider forcing the Coins tab to be shown when CashShuffle is activated ***if and only if* it never has been explicitly hidden by the user**
- Consider having default installs of Electron Cash show the Coins tab (and the Addresses tab). I've found most users find these tabs useful once they realize they exist.
- Or, implement #17

**Comment by fyookball** [comment]
I'm fine with this.  Traditionally UTXO tab hidden as its an advanced feature but makes more sense to show by default in the context of EC being a shuffling wallet.

**Comment by cculianu** [comment]
Ok so I have two options here because I can "tell" if the user ever explicitly hid it or not (if the config key for it is missing altogether it means the user never explicitly hid or has shown it).

I can:

1. Unconditionally show it (might be annoying for power users?).
2. Show it only if the user **never** explicitly "hid" it from the menu. This would mean that a default install for a user that didn't know it existed does the right thing and shows it -- but an install for a user that played with the option before would respect whatever he set there.

I'm ok with either, with a slight preference for (1) -- just laying out the options.

**Comment by cculianu** [comment]
Ok -- the latest commit does it.  If the Coins tab was never explicitly hidden by the user (ie, a default install or a user that never bothered to show then hide it again), it will detect this and auto-show the Coins tab when enabling CashShuffle.

If the coins tab was explicitly hidden sometime in the past (config key is present) -- it won't change anything and respect the user's wishes.

👍
