### ISSUE TITLE
Consider to only allow user to spend "Shuffled" coins (when CashShuffle is enabled only)

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#19]
This would 100% solve issue #14.

im_uname suggested this.

**Comment by imaginaryusername** [comment]
Yup, presumably when a user enables shuffle he/she wants to spend shuffled coins anyway, so only spending shuffled coins will be a desirable behavior that also solves the race condition. If user wants to spend unshuffled, he/she can easily one-click disable shuffle to do so.

On the send tab, there should be clear indications of what's going on:

"Shuffle is now active, you will only be sending privacy-enhanced coins!"

"Shuffle is disabled. You can send everything in your wallet, some payments might be trackable"

These should let a user know clearly why they sometimes have less coins to spend if shuffle is turned on.

**Comment by cculianu** [comment]
Yes! And perhaps in the Send tab is an additional UI path for the users to end up at the destination we want for them: "turning shuffling on". 

Not a bad way to go about it.



What's more I think we should offer a breakdown of amounts somewhere in the UI (perhaps the Send tab) when Shuffling is ON.  Something like:

Total Funds: xx BCH (+ yy unconfirmed)
Frozen Funds: yyy BCH
Unshuffled Funds: zzz BCH
Shuffled Funds (available for spending): www BCH

Etc..

**Comment by cculianu** [comment]
Note for me: This would make #14 & #15 obsolete if implemented.

**Comment by fyookball** [comment]
This is a pretty good idea! 

There is a downside though... and that is that a user may forget to re-enable CashShuffle in the event they turn it off to send some unshuffled or too-small-to-shuffle coins.

Given our challenge of liquidity and the imperative of having as many people have this on all the time as possible... I think it is a major drawback.  I don't want people having to turn off shuffling just to send unshuffled coins.   I'm scared of any encouragement to make the user turn off shuffling.
 
So I think we can maybe improve this idea but having another option to allow shuffled coins to be sent, which I think @cculianu suggested somewhere else.

**Comment by imaginaryusername** [comment]
Thing is... people can already disable shuffle one-click. Unless we remove that option, why not make the featureset less confusing? 

If I turn on shuffle, it should be clear to me "okay, I'm in private mode now, everything I do is mixed-ish and I'm safe-ish". If someone turn on shuffle yet get tracked anyway, I'd actually consider that a bad PR - people will just turn off shuffling altogether to save fees (not to mention stop getting weird unconfirmed outputs) if they find it confusing and pointless.

I think making sure you don't get tracked when shuffle is on actually enhances its appeal and will make more people want to keep it on, not the reverse. Just my two cents.

**Comment by cculianu** [comment]
@imaginaryusername You make a very convincing argument.  I am in your camp on this one and agree with your reasoning.  My two cents as well.

**Comment by cculianu** [comment]
This has been implemented.  Screenshot:

<img width="782" alt="screen shot 2018-12-11 at 2 47 44 pm" src="https://user-images.githubusercontent.com/266627/49802031-7f529980-fd54-11e8-8804-87883ccbaca5.png">
