### ISSUE TITLE
uses same change addr over and over

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#2]
Using a standard wallet, after ~50 shuffles, they *all* dumped the change onto the same address (change addr 0).

![screenshot from 2018-11-09 04-26-44](https://user-images.githubusercontent.com/36528214/48262751-8c3c4000-e3d8-11e8-8114-938283912180.png)

(screenshot was taken after I cleaned out my wallet, but, you can see all the tx counts)

**Comment by fyookball** [comment]
this is definitely not good @clifordsymack

**Comment by clifordsymack** [comment]
fixed
