### ISSUE TITLE
Core protocol code needs major fixes.

### ISSUE THREAD

**Issue by cculianu** [clifordsymack/Electron-Cash#21]
I began to review the core code that implements the protocol client (the code that talks to the server and does the shuffling). My overall impression is that while the code has some decent design patterns (use of 'Channels', an idea borrowed from Go), and it does make an attempt at using some decent design principles, it still leaves much to be desired in terms of robustness, reliability, and efficacy.

Some of the more obvious things that I noticed when looking at this code (this is not a full list yet):

1. It does not appear to be sufficiently resilient to errors and it just humms along like nothing's wrong even if the network disappears.

2. On first connect to a server if it fails (say because the network is down, etc) it just gives up and never sends any indication of this to the user. This needs to be addressed.

3. The socket code is worrisome.  It does things like sleeps in a thread for 100ms at a time polling a socket. That's very poor practice and not the right way to do sockets. That's an average of 50ms of time per protocol message that is wasted due to sleeping.  In a nutshell:  artificial latency is introduced to each outgoing protocol packet going down the wire of avg. 50ms.  For large shuffles this could lead to a shuffle that should have taken under 1 second to complete to take 7-10 seconds for no good technical reason! (See Commutator.run()). This needs to be addressed.  And a solution to this is **NOT** to busy-loop on the socket wasting CPU time -- but rather the optimal approach is to use blocking sockets with a timeout.  Summary: The socket handling code needs to be rewritten.

4. Race conditions. This code makes very minimal if any use of synchronization primitives such as mutexes.  It modifies the wallet and wallet storage from threads without ensuring no other thread is doing the same thing at the same time. Due to the way python does threads thankfully this won't lead to a crash (as it might in a lower level language such as C++) -- but it could lead to losing information and/or inconsistent states in higher-level application logic (classic race condition situation).  I am in particular worried about the frozen_due_to_cashshuffle lists put into wallet storage that don't have locks around them.  If 2 threads are reading/writing this variable at the same time, it could lead to lost information -- a classic race condition situation.

These are just some observations from looking over the code quickly.   I have not finished reviewing this code -- but my overall recommendation is that a lot more time needs to be spent on this code and that it is not ready to go out into the wild.

These problems will impact usability and reliability of the code and will lead to users being confused why their Cash Shuffles aren't shuffling and also will lead to major scaling/lag/slowdown issues for larger shuffles.

**Comment by cculianu** [comment]
UPDATE: I fixed some of the above-mentioned problems *a little bit* (such as the latency error talked about above).

But there are still race conditions all over the place and tons of questionable design choices.

Here is a great gem from this code:

https://github.com/clifordsymack/Electron-Cash/blob/b38cd82af8f84b2f82e8e0f9e055563c5f466190/plugins/shuffle/client.py#L281

^^ It's basically a busy loop with a 10ms sleep for polling internal data structures.  This is incredibly bad practice and bad engineering. It wastes cpu cycles because the programmer was too lazy or too inexperienced to think up a better design.

This needs to be changed.

**Comment by cculianu** [comment]
**UPDATE 2*** 

So far, I have fixed:

- 95% of the race conditions (I think). I still need to review the code more.  
- The socket code no longer adds artificial lag or burns the CPU polling.
- Refactored the code to be much clearer.
- Network code now gives up on server/protocol errors and allows for a fast restart/retry (every 10 seconds by default).  Previously it would take up to 5 mins for a retry.
- The UI now tells the user if there is a persistent network issue (eg server is down) -- a badge icon has been added to the UI. User can click on the icon and is prompted to select a different server.
- The ProtocolThread life cycle has been more clearly defined and it explicitly exits on errors.
- The 'WatchDog' thread was removed.  The watchdog pattern is typically used for monitoring outside hardware or systems outside your control where things can go down spuriously and without signaling you as they go down.  In this code, they aren't a good idea because we actually can detect any and all errors from worker threads and propagate that information back.  WatchDogs aren't needed.  Instead, the ProtocolThread lifecycle is more well defined. As a result:
    - If there's an error it no longer takes 5 minutes to retry a shuffle
    - Fixed an issue where in the middle of a shuffle the watchdog thread might just blindly delete a running thread.

I still need to work on this more but most of the more glaring issues I believe have been addressed.

What's still left: I haven't yet looked at the lower-level crypto/signing 'Round 1-5' code yet.  So that still needs review.

**Comment by fyookball** [comment]
Nice work!   Where's the badge icon btw? I don't even see that this github account has the icons repo.

**Comment by cculianu** [comment]
Yeah it doesn't use the icons repo yet... you have to run:

`pyrcc5 -o gui/qt/icons_rc.py icons.qrc`

To rebuild the icons.

It's annoying.

We will merge this into master anyway and update the electrum-icons then, I figure, right?

**Comment by fyookball** [comment]
Right but I also don't see the icon in the icons folder.  Am I looking in the wrong place?

**Comment by cculianu** [comment]
It's in the repo... so probably you are looking in the wrong place if you don't see it.

Where are you looking?

**Comment by cculianu** [comment]
This is the icon in this repo right now as I type this:

https://github.com/clifordsymack/Electron-Cash/blob/master/icons/cashshuffle_on_error.png

**Comment by fyookball** [comment]
ok i just scanned the time stamps, just didn't visually see it. thx :)

**Comment by cculianu** [comment]
I'm closing this issue as I believe most of this to be somewhat adequately handled now after significant efforts on my part. :)
