### ISSUE TITLE
Wishlist: merge coins when they come from same address

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#3]
If I have two coins on same address, valued 0.06 and 0.07, it should input them both into one shuffle at the 0.1-value tier. There is no privacy leak from combining coins from same address.

**Comment by fyookball** [comment]
This doesnt need to be fixed now (future version) but great idea

**Comment by fyookball** [comment]
Just reiterating again, this won't be fixed for this release.

**Comment by zquestz** [comment]
This is a great idea. =)

**Comment by imaginaryusername** [comment]
Per discussion in #96, this seems to be fixable alongside if we implement (1) there, which seems to be the preferable solution. Both can be closed together.
