### ISSUE TITLE
Cannot shuffle when being a proxy (failed to connect)

### ISSUE THREAD

**Issue by m4ktub** [clifordsymack/Electron-Cash#33]
In this latest version, when running on Windows, Cash Shuffle does not seem be able to connect to the shuffle server when the network connection goes through a proxy server. In previous versions (<2 weeks ago) shuffling worked as expected.

I've tried HTTP and SOCKS proxy servers. In both cases Electron Cash is connected, detects the network split, and works as intended for sends and receives. Also, in both cases the Cash Shuffle plugin is unable to connect to the _imaginary_ or _tartarusgroup_ servers.

_Figure 1: Connection problem reported in the status bar_
![image](https://user-images.githubusercontent.com/253588/49882188-fad14b00-fe27-11e8-9140-41afaa7caf27.png)

_Figure 2: Final connection error after choosing a server_
![038e5b36-10f4-4e97-b12f-1590db7f025e](https://user-images.githubusercontent.com/253588/49882210-06bd0d00-fe28-11e8-9803-9dba50ba1062.jpg)

**Comment by cculianu** [comment]
I didn't really touch the socket creation code and it should still pick up the monkey patches used by the SOCKS code in the core client... but I'll test it and figure it out.

Thanks.

**Comment by cculianu** [comment]
OK well I set up a SOCKS4 proxy here and it worked after my latest commit https://github.com/clifordsymack/Electron-Cash/commit/c82b47632cf4fdb09af8590707400e26dd0a7e9f

May I send you a Windows build sometime so you can tell me if it's really fixed for you?

**Comment by cculianu** [comment]
Ok, I built it with the fix:  https://c3-soft.com/downloads/BitcoinCash/Electron-Cash/CashShuffle/

Let me know!

**Comment by m4ktub** [comment]
I can confirm the fix. Now I can connect to `shuffle.imaginary.cash [ssl]` with a configured proxy. It validates the connection, Cash Shuffle is shown as "on", and there are no error icons in the status bar. I've cut the connection and the plugin shows the connection error after a while and unfreezes any coins. After the connection is reestablished it resumes operations as expected. Changing proxy server also seems to work as expected.

**Comment by cculianu** [comment]
Oh that's awesome.  Phew!  Note that I should increase the timeout for initial connection if via proxy -- so as to allow TOR users  more time.

Thanks for testing!
