### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#4]
I am seeing CPU usage at 100% all the time (as if 1 core maxed out).

Note that EC currently imports two **really** slow and CPU-intensive cryptographic libraries (pyaes and ecdsa). If the shuffler is making any usage of cryptographic facilities then this may be the reason.

(BTW I tried running `apt install python3-pycryptodome` but it seems to not change anything.)

**Comment by dskloet** [comment]
Shouldn't this be filed at https://github.com/Electron-Cash/Electron-Cash/issues ?

**Comment by fyookball** [comment]
no this is for Cash Shuffle implementation @dskloet

**Comment by fyookball** [comment]
@clifordsymack is this fixed?

**Comment by clifordsymack** [comment]
@ yes it is fixed
