### ISSUE TITLE
PyQt5.sip module not found on linux install

### ISSUE THREAD

**Issue by christroutner** [clifordsymack/Electron-Cash#55]
Trying to follow the directions in the README on Ubuntu 18.04. Got this error message when trying to execute `./electron-cash`:

```
Traceback (most recent call last):
  File "./electron-cash", line 378, in <module>
    d.init_gui(config, plugins)
  File "/home/trout/Electron-Cash/lib/daemon.py", line 301, in init_gui
    gui = __import__('electroncash_gui.' + gui_name, fromlist=['electroncash_gui'])
  File "/home/trout/Electron-Cash/gui/qt/__init__.py", line 33, in <module>
    from PyQt5.QtGui import *
ModuleNotFoundError: No module named 'PyQt5.sip'

```

**Comment by cculianu** [comment]
Try any of the following:

```
sudo pip3 install -I pyqt5
# or
sudo pip3 install -I pyqt5-sip
# or
sudo pip3 uninstall pyqt5
sudo pip3 uninstall pyqt5-sip
sudo pip3 install pyqt5
```

There's some packaging issue with PyQt5 on some Ubuntus.. I guess. Let me know if it works or not.

**Comment by cculianu** [comment]
Also.. FWIW.. I ditched Ubuntu 18.04 LTS and am on 18.10 non-LTS and am happier.  LTS is for server operators or something.  Too many old packages for desktop users on the bleeding edge like us!

**Comment by christroutner** [comment]
Progress! Here are the commands I had to run in order to get the Cash Shuffle fork of Electron Cash to run in Ubuntu 18.04:

```
sudo apt-get install -y python3-pip python3-setuptools
sudo python3 setup.py install
sudo pip3 install -I pyqt5
```

**Comment by cculianu** [comment]
Awesome! Glad it worked.  Will pin this one.
