### ISSUE TITLE
Faulty balance when spending selected unshuffled coins

### ISSUE THREAD

**Issue by acidsploit** [clifordsymack/Electron-Cash#60]
When you have cashshuffle running select unshuffled coin to spend. The select spend unshuffled, hit max, and total unshuffled balance is calculated instead of the selected coins balance.

1. go to spend, select spend shuffled
 2. go to coins, select one "in queue"
 > spend
 3. hit max in the spend window
 > selects nothing
4. click "spend uinshuffled
> selects all unfrozen balance

**Comment by cculianu** [comment]
Related to #48 

See video (provided by @acidsploit ):



![coins_bug_cashshuffle 2](https://user-images.githubusercontent.com/266627/53285781-5e072400-376d-11e9-8658-c76863c703e7.gif)

**Comment by cculianu** [comment]
I'm pretty sure I fixed this in the latest commit.  Thanks a lot for bringing this to my attention!

If you see any issues with the fix let me know  and we can re-open this issue!
