### ISSUE TITLE
Sign source code releases

### ISSUE THREAD

**Issue by haplo** [clifordsymack/Electron-Cash#61]
I was going to download the plugin for use in Linux, but there are no signatures for the source code files (.zip and .tar.gz).

Please provide signatures for those files so Linux users can verify the download. And/or if it's easier then sign commits and tags in git.

**Comment by cculianu** [comment]
Hmm. I can look into that later today.  Note the source code is just the bare sources -- I didn't do a python source build (where it grabs all 'packages' and puts them in a subdir called packages/).

If you want me to do that let me know.

**Comment by cculianu** [comment]
I updated the release to contain the sourcecode.  It's the one that ends in .tar.gz which has a .sig and a .sha256sum.

**Comment by haplo** [comment]
Thanks for the quick turnaround @cculianu!
