### ISSUE TITLE
Auto-shuffling failing on version 3.3.6 Release Build #12

### ISSUE THREAD

**Issue by caellach** [clifordsymack/Electron-Cash#62]
I am running on Ubuntu 16.04, all packages on the system and in python3 pip are currently up to date.

I tried to connect to the other server (cashshuffle.c3-soft.com) to test but it appears to be having some issues when connecting and currently has no one else connected that I can test a shuffle with.

This is the verbose output when it fails. I've replaced addresses & transaction id's w/ asterisks.
The address being selected for use has more than 1 BCH in it & the output + change addresses are valid in my wallet and haven't been used. This error keeps repeating.
Let me know what other information I can provide to help fix this issue.

> |1069.463| [BackgroundShufflingThread (874240) <wallet_moving>] Scale 100000000 Coin \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*:0 OutAddr \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* Change \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* make_protocol_thread
|1069.477| [profiler] get_shuffled_and_unshuffled_coins 0.0018
|1071.075| [shuffle.servo.cash] SSL certificate signed by CA
|1071.075| [shuffle.servo.cash] connected
|1073.262| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Player 5 get session number.'
|1073.262| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Player 5 joined the pool!'
|1073.680| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Player 6 joined the pool!'
|1077.401| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Player 7 joined the pool!'
|1077.741| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Player 8 joined the pool!'
|1137.800| [Comm (866048) <shuffle.servo.cash:1337> <Scale: 100000000>] Socket timeout (60.0): The read operation timed out
|1137.800| [ProtocolThread (866048) <Scale: 100000000> ] Exception in 'run': The read operation timed out
|1137.800| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Error: cannot complete the pool'
|1137.800| [BackgroundShufflingThread (866048) <wallet_moving>] Signalling stop for scale: 100000000
|1137.800| [BackgroundShufflingThread (866048) <wallet_moving>] Scale: 100000000 Message: 'Exit: Scale '100000000' Coin '****************************************************************:0''
|1137.801| [BackgroundShufflingThread (874240) <wallet_moving>] Stop protocol thread for scale: 100000000
|1137.801| [BackgroundShufflingThread (866048) <wallet_moving>] Signalling stop for scale: 100000000
|1137.801| [Comm (874240) <shuffle.servo.cash:1337> <Scale: 100000000>] Closing comm (subsequent socket errors are to be expected)
|1137.803| [profiler] get_shuffled_and_unshuffled_coins 0.0014
|1137.805| [ProtocolThread (874240) <Scale: 100000000> ] Joined self
|1137.806| [BackgroundShufflingThread (874240) <wallet_moving>] Stop protocol thread for scale: 100000000
|1137.806| [BackgroundShufflingThread (874240) <wallet_moving>] Thread already exited; cleaned up.

**Comment by cculianu** [comment]
This is normal operation and not really an error.  The verbose output seems alarmist with all the "Errors" but they are really just normal socket timeouts.

Really connect to the other server: servo.cash -- it has all the people on it! 🗡

**Comment by caellach** [comment]
As per the log, I am connected to servo.cash. I assume the timeout is occurring because there aren't enough players for my pool. I'll leave my client up for the day and see what happens. Thanks.

**Comment by cculianu** [comment]
Yeah the timeout happens every minute, where it disconnects and tries again.

We're doing a 10-pool-size test.

Yes! Please leave it on! We plan on leaving it on all weekend.  We never tried a test this big and right now not a lot of people have it installed so that's why it's not finding players.  But if you leave it on.. and more people show up.. we may get shuffles going!!
