### ISSUE TITLE
Warning when choosing to spend unshuffled coins

### ISSUE THREAD

**Issue by imaginaryusername** [clifordsymack/Electron-Cash#71]
When choosing radio button to send "unshuffled" coins, there should be a fat warning (perhaps in the form of a popup, so it cannot be ignored). Spending unshuffled is not only privacy reducing for incoming coins, but also potentially compromise coins from past shuffles - change from spending shuffled outputs are binned together with incoming coins. There are longer term fixes that address this, but before it can be addressed, the UI should discourage people from spending unshuffled. 

Possible text: 

"You are now spending UNSHUFFLED coins. Spending and linking these coins may compromise your privacy not only for new received coins, but also from your past spending of shuffled coins. Are you sure?"

**Comment by cculianu** [comment]
I do think it's surprisingly easy for nubs to spend unshuffled if the app has remained in that state.

I can easily add this popup with a little tiny 'don't ask me this again' in the corner (only to be polite, of course).

I am having trouble understanding this though:

> Spending unshuffled is not only privacy reducing for incoming coins, but also potentially compromise coins from past shuffles - change from spending shuffled outputs are binned together with incoming coins.

I'm having trouble wrapping my head around this one... wouldn't an easy fix be just to always use a brand spanking new change address for each spending tx?

**Comment by imaginaryusername** [comment]
@cculianu yes, using a new change address is default behavior already, but when spending larger amounts you'll combine coins (in the same bucket), and that's where troubles begin. 😬

**Comment by cculianu** [comment]
@imaginaryusername  Hmm... I'm still having trouble understanding this but chainalysis woes are not my forte.  :)

Here is what it looks like now on macOS.  I'm getting ready to commit this dialog.  Note it pops up whenever you select that radio and even if you left that mode "on" last run, next run it pops up again..

<img width="984" alt="screen shot 2019-02-27 at 6 38 28 pm" src="https://user-images.githubusercontent.com/266627/53506648-17902d00-3abf-11e9-810f-bacb3c0d70dd.png">
