### ISSUE TITLE
Status update failed

### ISSUE THREAD

**Issue by clifordsymack** [clifordsymack/Electron-Cash#8]
Here is a sequence of steps to reproduce the error:
1) start the cashshuffle plugin
2) go to coins tab
3) press sort button on the shuffling status field
4) when player enter the pool few seconds later some statuses disappear
The 
![2018-11-30 17-43-50](https://user-images.githubusercontent.com/34399329/49295780-9fb66480-f4c7-11e8-9297-30c25c4585fc.png)

**Comment by cculianu** [comment]
I committed some changes that maybe will fix it  -- changes make it so that we are updating the item from a hook now before it's added to the TreeWidget.

Let me know if this fixes it!

**Comment by cculianu** [comment]
I think we can close this now.. right?
