### ISSUE TITLE
Warning when disabling Cashshuffle plugin

### ISSUE THREAD

**Issue by imaginaryusername** [clifordsymack/Electron-Cash#80]
Similar to #71 , when clicking (or at password failure) resulting in cashshuffle status going from enabled -> disabled, there should be a popup that warns users. Potential text:

"You are now disabling Cashshuffle plugin on a wallet that had it enabled. Spending and linking coins may compromise your privacy for both unshuffled and shuffled coins in this wallet. Are you sure?"

If "No" is clicked, ideally the response differs according to what happened before (if manual disable, it reverts to enabled; if password failure, password is prompted again). If that is complicated to implement, though, the dialogue can forgo the "No" button and just have an "I understand" button.

**Comment by cculianu** [comment]
Okay.  I guess we're really hammering home this "unshuffled is bad.. mmmmkayyy" message, huh? :)

I might  not nag users about it until they have at least completed 1 shuffle and/or only nag them if it truly is a situation where they have had the plugin "on" in the past.   

Although that adds a bit of noise to the code -- so I may just nag unconditionally... we'll see.  But I guess I am going to do this - despite my dislike for nag screens in general... it feels.. Applesque. :)

**Comment by cculianu** [comment]
Password prompt cancelled nag (only appears if the internal per-wallet cashshuffle session counter is >0):

<img width="436" alt="screen shot 2019-02-28 at 11 29 40 am" src="https://user-images.githubusercontent.com/266627/53556263-2a9d0e80-3b4c-11e9-889f-e56ec651be37.png">


Generic disable nag if clicking icon, etc:

<img width="426" alt="screen shot 2019-02-28 at 11 31 42 am" src="https://user-images.githubusercontent.com/266627/53556418-764fb800-3b4c-11e9-844d-6ff4f204b76c.png">

Let me know what you think @imaginaryusername -- I'm still testing this but getting ready to push this commit out.
