### ISSUE TITLE
Switch positions in Cashshuffle right click menu

### ISSUE THREAD

**Issue by imaginaryusername** [clifordsymack/Electron-Cash#91]
Very minor nit: I think the position of View Pools/Cashshuffle-settings and "Disable Cashshuffle" should be switched in the right-click menu on the cashshuffle button. Right now Disable Cashshuffle is in the default position, which meant I often accidentally click it when I wanted to adjust settings or view pools.

Disabling cashshuffle is already accessible by left-clicking the button anyway, so the menu could really move it away from the easiest-to-click position. Whether left clicking behavior should be changed is a whole other issue. =)

**Comment by cculianu** [comment]
You got it. It's always an artform guessing where the best positions for these menu items are. I'll do it tomorrow or Monday.
