### ISSUE TITLE
Replace SHA-224 with SHA-256d

### ISSUE THREAD

**Issue by fyookball** [clifordsymack/Electron-Cash#98]
Please use a double round of sha-256, bitcoin style rather than SHA-224 when computing hash of the transaction.

this will prevent theoretical extention attacks and bring code more in line with bitcoin standards.

**Comment by cculianu** [comment]
You got it.  So protocol version 300 it is! Third time's a charm (I hope)!

**Comment by cculianu** [comment]
See #104 .  I'll merge this later today.  Don't merge it yet.. i'm still testing other stuff. :)

**Comment by cculianu** [comment]
IT IS DONE.
